#!/usr/bin/env python
"""Generate the self-contained Kaggle notebook for the BioNano-Sim data run.

The notebook does not import this repository. Everything it needs -- structure
preparation, the steered-MD pull, the damage proxy, the stiffness fit, the label
aggregation and the model -- is inlined, so it runs on a bare Kaggle GPU session
with only pip installs and internet enabled.

    python notebooks/build_kaggle_notebook.py
"""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "bionano_kaggle_pipeline.ipynb"


def md(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": list(lines),
    }


CELLS = [
    md(
        "# BioNano-Sim - paired mechanical experiments and the ML model\n",
        "\n",
        "Runs the whole pipeline on one Kaggle GPU session:\n",
        "\n",
        "1. Fetch the five approved structures from RCSB\n",
        "2. Compute per-residue features and rank damage candidates\n",
        "3. For each (protein, seed): equilibrate **once**, run the pristine pull, then\n",
        "   run every damaged variant from that **same** equilibrated conformation\n",
        "4. Fit stiffness from each force-extension curve\n",
        "5. Aggregate seeds into labels with a standard error, and gate on it\n",
        "6. Train XGBoost with held-out-protein CV and report honest metrics\n",
        "\n",
        "## Read this before trusting any number\n",
        "\n",
        "* The pull is **non-equilibrium steered MD** at ~0.03 nm/ps, roughly a million\n",
        "  times faster than an AFM experiment. Absolute forces are far above\n",
        "  experimental values. Only comparisons under this identical protocol mean\n",
        "  anything.\n",
        "* The damage proxy is a **controlled side-chain truncation**, not radiation\n",
        "  chemistry. No dose, LET or fluence value is used anywhere.\n",
        "* `scenario_id` does **not** enter the simulation, so it is metadata only and\n",
        "  must not be used as a model feature.\n",
        "* Measured run-to-run label noise on 1UBQ was ~27 percentage points. The seed\n",
        "  count below is what buys the label its precision; the notebook reports the\n",
        "  standard error so you can see whether a label is usable.\n",
        "\n",
        "**Settings:** turn on GPU (T4 or P100) and Internet in the notebook sidebar.",
    ),
    md("## 1. Setup"),
    code(
        "!pip -q install openmm biopython xgboost 2>&1 | tail -2\n",
        "\n",
        "import json, math, time, hashlib, itertools, warnings\n",
        "from pathlib import Path\n",
        "import numpy as np, pandas as pd\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "import openmm as mm\n",
        "from openmm import app, unit\n",
        "\n",
        "names = [mm.Platform.getPlatform(i).getName() for i in range(mm.Platform.getNumPlatforms())]\n",
        "print('OpenMM', mm.version.version, '| platforms:', names)\n",
        "PLATFORM_NAME = next((p for p in ('CUDA', 'OpenCL', 'CPU') if p in names), 'CPU')\n",
        "print('using:', PLATFORM_NAME)\n",
        "\n",
        "WORK = Path('/kaggle/working'); WORK.mkdir(exist_ok=True, parents=True)\n",
        "PDB_DIR = WORK / 'pdb'; PDB_DIR.mkdir(exist_ok=True)",
    ),
    md("## 2. Structures"),
    code(
        "import urllib.request\n",
        "\n",
        "# The five approved seed proteins, plus small single-domain structures that\n",
        "# widen the group axis. Held-out-protein CV is only as strong as the NUMBER of\n",
        "# proteins: with five there are five folds of one protein each, far too few to\n",
        "# claim generalisation. Every extra protein is another whole fold.\n",
        "#\n",
        "# Cost is linear in proteins. Trim EXTRA if the session runs short: CORE first.\n",
        "CORE = {\n",
        "    '1TIT': {'chain': 'A', 'uniprot': 'Q8WZ42', 'role': 'molecular spring'},\n",
        "    '1TEN': {'chain': 'A', 'uniprot': 'P24821', 'role': 'structural'},\n",
        "    '2SPC': {'chain': 'A', 'uniprot': 'P13395', 'role': 'elastic linker'},\n",
        "    '1UBQ': {'chain': 'A', 'uniprot': 'P0CG48', 'role': 'switch body'},\n",
        "    '1PGA': {'chain': 'A', 'uniprot': 'P06654', 'role': 'stable module'},\n",
        "}\n",
        "EXTRA = {\n",
        "    '1SHG': {'chain': 'A', 'uniprot': 'P07751', 'role': 'SH3 domain'},\n",
        "    '1CSP': {'chain': 'A', 'uniprot': 'P32081', 'role': 'cold-shock barrel'},\n",
        "    '1BPI': {'chain': 'A', 'uniprot': 'P00974', 'role': 'protease inhibitor'},\n",
        "    '1ENH': {'chain': 'A', 'uniprot': 'P02836', 'role': 'homeodomain'},\n",
        "    '1BDD': {'chain': 'A', 'uniprot': 'P38507', 'role': 'three-helix bundle'},\n",
        "    '1VII': {'chain': 'A', 'uniprot': 'P68104', 'role': 'villin headpiece'},\n",
        "    '2CI2': {'chain': 'I', 'uniprot': 'P01053', 'role': 'inhibitor domain'},\n",
        "    '1WIT': {'chain': 'A', 'uniprot': 'Q23551', 'role': 'twitchin Ig'},\n",
        "    '1AKI': {'chain': 'A', 'uniprot': 'P00698', 'role': 'lysozyme'},\n",
        "    '1E0L': {'chain': 'A', 'uniprot': 'P39019', 'role': 'WW domain'},\n",
        "    '1FNF': {'chain': 'A', 'uniprot': 'P02751', 'role': 'fibronectin III'},\n",
        "    '1QLX': {'chain': 'A', 'uniprot': 'P04156', 'role': 'prion globular domain'},\n",
        "}\n",
        "PROTEINS = {**CORE, **EXTRA}\n",
        "MAX_RESIDUES = 200      # keep runs short; big domains dominate the budget\n",
        "\n",
        "for pdb_id in list(PROTEINS):\n",
        "    dest = PDB_DIR / f'{pdb_id}.pdb'\n",
        "    try:\n",
        "        if not dest.exists():\n",
        "            urllib.request.urlretrieve(\n",
        "                f'https://files.rcsb.org/download/{pdb_id}.pdb', dest)\n",
        "        print(f'{pdb_id}: {dest.stat().st_size:,} bytes')\n",
        "    except Exception as exc:\n",
        "        print(f'{pdb_id}: DOWNLOAD FAILED ({exc}) -- dropped')\n",
        "        PROTEINS.pop(pdb_id)\n",
        "print(f'\\n{len(PROTEINS)} structures downloaded')",
    ),
    md(
        "## 3. Structure preparation\n",
        "\n",
        "One chain, one model, standard residues with a CA, no waters or ligands.",
    ),
    code(
        "STANDARD_AA = {'ALA','ARG','ASN','ASP','CYS','GLN','GLU','GLY','HIS','ILE',\n",
        "               'LEU','LYS','MET','PHE','PRO','SER','THR','TRP','TYR','VAL'}\n",
        "\n",
        "def prepare(src: Path, dest: Path, chain_id: str) -> Path:\n",
        "    \"\"\"Write a clean single-chain PDB. Keeps the first altloc only.\"\"\"\n",
        "    keep, seen_model = [], False\n",
        "    have_ca = set()\n",
        "    for line in src.read_text().splitlines():\n",
        "        if line.startswith('ENDMDL'):\n",
        "            seen_model = True\n",
        "            continue\n",
        "        if seen_model or not line.startswith('ATOM'):\n",
        "            continue\n",
        "        if line[21:22].strip() != chain_id or line[17:20].strip() not in STANDARD_AA:\n",
        "            continue\n",
        "        if line[16:17] not in (' ', 'A'):\n",
        "            continue\n",
        "        if line[12:16].strip() == 'CA':\n",
        "            have_ca.add(line[22:27])\n",
        "        keep.append(line)\n",
        "    keep = [ln for ln in keep if ln[22:27] in have_ca]\n",
        "    dest.write_text('\\n'.join(keep) + '\\nEND\\n')\n",
        "    return dest\n",
        "\n",
        "def chains_in(src: Path) -> dict:\n",
        "    counts = {}\n",
        "    for ln in src.read_text().splitlines():\n",
        "        if ln.startswith('ATOM') and ln[12:16].strip() == 'CA':\n",
        "            c = ln[21:22].strip()\n",
        "            counts[c] = counts.get(c, 0) + 1\n",
        "    return counts\n",
        "\n",
        "for pdb_id, meta in list(PROTEINS.items()):\n",
        "    src = PDB_DIR / f'{pdb_id}.pdb'\n",
        "    counts = chains_in(src)\n",
        "    if not counts:\n",
        "        print(f'{pdb_id}: no CA atoms -- dropped'); PROTEINS.pop(pdb_id); continue\n",
        "    if counts.get(meta['chain'], 0) < 20:\n",
        "        # The deposited file may not use the chain we assumed; take the largest.\n",
        "        meta['chain'] = max(counts, key=counts.get)\n",
        "        print(f\"{pdb_id}: falling back to chain {meta['chain']}\")\n",
        "    p = prepare(src, WORK / f'{pdb_id}_prepared.pdb', meta['chain'])\n",
        "    n = sum(1 for ln in p.read_text().splitlines() if ln[12:16].strip() == 'CA')\n",
        "    if not 20 <= n <= MAX_RESIDUES:\n",
        "        print(f'{pdb_id}: {n} residues outside 20-{MAX_RESIDUES} -- dropped')\n",
        "        PROTEINS.pop(pdb_id); continue\n",
        "    print(f\"{pdb_id}: chain {meta['chain']}, {n} residues\")\n",
        "\n",
        "print(f'\\n{len(PROTEINS)} proteins prepared -> {len(PROTEINS)} CV groups')",
    ),
    md(
        "## 4. Per-residue features and damage candidates\n",
        "\n",
        "Computed here rather than loaded, so features and damage targets stay\n",
        "consistent with each other. The candidate score is\n",
        "`0.45*sasa_norm + 0.30*inverse_packing + 0.25*susceptibility`.",
    ),
    code(
        "from Bio.PDB import PDBParser, ShrakeRupley\n",
        "\n",
        "HYDROPHOBIC = set('AFILMVWY')\n",
        "CHARGED = set('DEKR')\n",
        "THREE_TO_ONE = {'ALA':'A','ARG':'R','ASN':'N','ASP':'D','CYS':'C','GLN':'Q','GLU':'E',\n",
        "                'GLY':'G','HIS':'H','ILE':'I','LEU':'L','LYS':'K','MET':'M','PHE':'F',\n",
        "                'PRO':'P','SER':'S','THR':'T','TRP':'W','TYR':'Y','VAL':'V'}\n",
        "AA_MASS = {'A':71.08,'R':156.19,'N':114.10,'D':115.09,'C':103.14,'Q':128.13,'E':129.12,\n",
        "           'G':57.05,'H':137.14,'I':113.16,'L':113.16,'K':128.17,'M':131.19,'F':147.18,\n",
        "           'P':97.12,'S':87.08,'T':101.10,'W':186.21,'Y':163.18,'V':99.13}\n",
        "SUSCEPTIBILITY = {**{a: 'high' for a in 'CHMWY'},\n",
        "                  **{a: 'medium' for a in 'RNQKFPST'},\n",
        "                  **{a: 'low' for a in 'ADEGILV'}}\n",
        "SUSC_SCORE = {'high': 1.00, 'medium': 0.60, 'low': 0.25}\n",
        "\n",
        "# The proxy removes a side chain, so residues without one cannot be targets.\n",
        "NO_SIDE_CHAIN = {'GLY', 'ALA'}\n",
        "EXCLUDED = {'PRO'}          # its ring closes onto the backbone nitrogen\n",
        "\n",
        "def residue_features(prepared: Path, chain_id: str) -> pd.DataFrame:\n",
        "    structure = PDBParser(QUIET=True).get_structure('p', str(prepared))\n",
        "    model = structure[0]\n",
        "    residues = [r for r in model[chain_id] if r.get_resname() in STANDARD_AA and r.has_id('CA')]\n",
        "    ShrakeRupley().compute(model, level='R')\n",
        "\n",
        "    seq = ''.join(THREE_TO_ONE[r.get_resname()] for r in residues)\n",
        "    n = len(residues)\n",
        "    coords = np.array([r['CA'].get_coord() for r in residues], dtype=float)\n",
        "    d = np.linalg.norm(coords[:, None, :] - coords[None, :, :], axis=-1)\n",
        "    np.fill_diagonal(d, np.inf)\n",
        "    contacts = (d <= 8.0).sum(axis=1)          # 8 A CA-CA, self excluded\n",
        "\n",
        "    sasa = np.array([r.sasa for r in residues], dtype=float)\n",
        "    rng = sasa.max() - sasa.min()\n",
        "    sasa_norm = (sasa - sasa.min()) / rng if rng > 0 else np.zeros_like(sasa)\n",
        "    inv_pack = 1.0 - contacts / contacts.max() if contacts.max() else np.zeros(n)\n",
        "    susc = np.array([SUSC_SCORE[SUSCEPTIBILITY[c]] for c in seq])\n",
        "    score = 0.45 * sasa_norm + 0.30 * inv_pack + 0.25 * susc\n",
        "\n",
        "    df = pd.DataFrame({\n",
        "        'residue_seq': [r.get_id()[1] for r in residues],\n",
        "        'residue_type': [r.get_resname() for r in residues],\n",
        "        'residue_index_norm': np.arange(n) / (n - 1),\n",
        "        'residue_sasa_norm': sasa_norm,\n",
        "        'residue_contact_count': contacts.astype(float),\n",
        "        'qualitative_susceptibility': [SUSCEPTIBILITY[c] for c in seq],\n",
        "        'candidate_score': score,\n",
        "        'protein_length': float(n),\n",
        "        'molecular_weight': float(sum(AA_MASS[c] for c in seq) + 18.02),\n",
        "        'hydrophobic_fraction': sum(c in HYDROPHOBIC for c in seq) / n,\n",
        "        'charged_fraction': sum(c in CHARGED for c in seq) / n,\n",
        "    })\n",
        "    df = df.sort_values('candidate_score', ascending=False).reset_index(drop=True)\n",
        "    df['proxy_rank'] = np.arange(1, len(df) + 1)\n",
        "    return df\n",
        "\n",
        "FEATURES = {}\n",
        "for pdb_id, meta in list(PROTEINS.items()):\n",
        "    try:\n",
        "        FEATURES[pdb_id] = residue_features(\n",
        "            WORK / f'{pdb_id}_prepared.pdb', meta['chain'])\n",
        "    except Exception as exc:\n",
        "        print(f'{pdb_id}: featurisation failed ({type(exc).__name__}) -- dropped')\n",
        "        PROTEINS.pop(pdb_id); continue\n",
        "    top = FEATURES[pdb_id].head(3)\n",
        "    print(pdb_id, '->', ', '.join(f\"{r.residue_type}{r.residue_seq}\" for r in top.itertuples()))",
    ),
    md("## 5. The damage proxy"),
    code(
        "BACKBONE_KEEP = {'N', 'CA', 'C', 'O', 'OXT', 'CB'}\n",
        "\n",
        "def eligible(residue_type: str, seq: int, pull_seqs) -> bool:\n",
        "    \"\"\"A target must have a side chain and must not be a pulling attachment point.\"\"\"\n",
        "    if residue_type in NO_SIDE_CHAIN or residue_type in EXCLUDED:\n",
        "        return False\n",
        "    return seq not in pull_seqs\n",
        "\n",
        "def apply_damage(src: Path, dest: Path, chain_id: str, seqs) -> dict:\n",
        "    \"\"\"Truncate each target side chain to CB and rename the residue ALA.\n",
        "\n",
        "    Every atom outside the target residues is copied byte-for-byte, so the\n",
        "    damaged structure differs from its baseline by the side chains and nothing\n",
        "    else.\n",
        "    \"\"\"\n",
        "    seqs = set(seqs)\n",
        "    kept, removed = [], []\n",
        "    for line in src.read_text().splitlines():\n",
        "        if not line.startswith('ATOM'):\n",
        "            kept.append(line); continue\n",
        "        seq = line[22:26].strip()\n",
        "        if not (line[21:22].strip() == chain_id and seq.isdigit() and int(seq) in seqs):\n",
        "            kept.append(line); continue\n",
        "        if line[12:16].strip() not in BACKBONE_KEEP:\n",
        "            removed.append(line[12:16].strip()); continue\n",
        "        kept.append(line[:17] + 'ALA' + line[20:])\n",
        "    dest.write_text('\\n'.join(kept) + '\\n')\n",
        "    return {'n_residues_damaged': len(seqs), 'n_atoms_removed': len(removed),\n",
        "            'damage_residue_ids': ' '.join(f'{chain_id}:{s}' for s in sorted(seqs)),\n",
        "            'atoms_removed': sorted(removed)}",
    ),
    md(
        "## 6. Simulation core\n",
        "\n",
        "Constant-velocity steered MD on the N-to-C terminal Ca distance. The reaction\n",
        "coordinate is an interatomic distance, so it is invariant under translation and\n",
        "rotation and nothing has to be pinned in the lab frame.",
    ),
    code(
        "KJ_PER_MOL_NM_IN_PN = 1000.0 / (6.02214076e23 * 1.0e-9) * 1.0e12   # = 1.6605390672\n",
        "\n",
        "PROTOCOL = dict(\n",
        "    forcefield=('amber14-all.xml', 'implicit/gbn2.xml'),\n",
        "    temperature_k=300.0, friction_per_ps=1.0, timestep_fs=2.0,\n",
        "    nonbonded_cutoff_nm=1.2,\n",
        "    minimisation_steps=1000, shared_equilibration_steps=5000,\n",
        "    settle_steps=1000,               # after damage, before pulling\n",
        "    pull_steps=20000,                # 40 ps\n",
        "    spring_k_kj_mol_nm2=1000.0,      # = 1660.539 pN/nm\n",
        "    pull_velocity_nm_per_ps=0.03,\n",
        "    restraint_update_steps=10, sample_interval_steps=20,\n",
        "    fit_block_size=25, fit_noise_multiple=3.0,\n",
        ")\n",
        "PROTOCOL_HASH = hashlib.sha256(\n",
        "    json.dumps(PROTOCOL, sort_keys=True, default=str).encode()).hexdigest()\n",
        "print('protocol hash', PROTOCOL_HASH[:16])\n",
        "\n",
        "def build(pdb_path: Path, seed: int):\n",
        "    pdb = app.PDBFile(str(pdb_path))\n",
        "    ff = app.ForceField(*PROTOCOL['forcefield'])\n",
        "    modeller = app.Modeller(pdb.topology, pdb.positions)\n",
        "    modeller.addHydrogens(ff)\n",
        "    system = ff.createSystem(\n",
        "        modeller.topology, constraints=app.HBonds, rigidWater=True,\n",
        "        removeCMMotion=True, nonbondedMethod=app.CutoffNonPeriodic,\n",
        "        nonbondedCutoff=PROTOCOL['nonbonded_cutoff_nm'] * unit.nanometer)\n",
        "    integrator = mm.LangevinMiddleIntegrator(\n",
        "        PROTOCOL['temperature_k'] * unit.kelvin,\n",
        "        PROTOCOL['friction_per_ps'] / unit.picosecond,\n",
        "        PROTOCOL['timestep_fs'] * unit.femtoseconds)\n",
        "    integrator.setRandomNumberSeed(int(seed))\n",
        "    sim = app.Simulation(modeller.topology, system, integrator,\n",
        "                         mm.Platform.getPlatformByName(PLATFORM_NAME))\n",
        "    sim.context.setPositions(modeller.positions)\n",
        "    return sim\n",
        "\n",
        "def ca_indices(topology):\n",
        "    return [a.index for a in topology.atoms() if a.name == 'CA']\n",
        "\n",
        "def write_pdb(sim, dest: Path):\n",
        "    with dest.open('w') as fh:\n",
        "        app.PDBFile.writeFile(\n",
        "            sim.topology, sim.context.getState(getPositions=True).getPositions(), fh)\n",
        "\n",
        "def equilibrate(pdb_path: Path, seed: int, steps: int, dest: Path):\n",
        "    sim = build(pdb_path, seed)\n",
        "    sim.minimizeEnergy(maxIterations=PROTOCOL['minimisation_steps'])\n",
        "    sim.context.setVelocitiesToTemperature(PROTOCOL['temperature_k'] * unit.kelvin, int(seed))\n",
        "    if steps:\n",
        "        sim.step(steps)\n",
        "    write_pdb(sim, dest)\n",
        "    return dest",
    ),
    code(
        "def steered_pull(pdb_path: Path, seed: int):\n",
        "    \"\"\"Settle briefly, then pull. Returns the force-extension curve.\"\"\"\n",
        "    sim = build(pdb_path, seed)\n",
        "    sim.minimizeEnergy(maxIterations=200)\n",
        "    sim.context.setVelocitiesToTemperature(PROTOCOL['temperature_k'] * unit.kelvin, int(seed))\n",
        "    sim.step(PROTOCOL['settle_steps'])\n",
        "\n",
        "    ca = ca_indices(sim.topology)\n",
        "    a, b = ca[0], ca[-1]\n",
        "    pos = sim.context.getState(getPositions=True).getPositions(asNumpy=True).value_in_unit(unit.nanometer)\n",
        "    d0 = float(np.linalg.norm(np.asarray(pos[b]) - np.asarray(pos[a])))\n",
        "\n",
        "    k = PROTOCOL['spring_k_kj_mol_nm2']\n",
        "    force = mm.CustomBondForce('0.5*k_pull*(r - r0_pull)^2')\n",
        "    force.addGlobalParameter('k_pull', k)\n",
        "    force.addGlobalParameter('r0_pull', d0)\n",
        "    force.addBond(a, b, [])\n",
        "    sim.system.addForce(force)\n",
        "    sim.context.reinitialize(preserveState=True)   # the Context caches the System\n",
        "\n",
        "    v, dt = PROTOCOL['pull_velocity_nm_per_ps'], PROTOCOL['timestep_fs'] / 1000.0\n",
        "    upd, samp = PROTOCOL['restraint_update_steps'], PROTOCOL['sample_interval_steps']\n",
        "    rows, done, remaining = [], 0, PROTOCOL['pull_steps']\n",
        "    while remaining > 0:\n",
        "        chunk = min(upd, remaining)\n",
        "        r0 = d0 + v * (done * dt)\n",
        "        sim.context.setParameter('r0_pull', r0)\n",
        "        sim.step(chunk)\n",
        "        remaining -= chunk; done += chunk\n",
        "        if done % samp and remaining:\n",
        "            continue\n",
        "        st = sim.context.getState(getPositions=True)\n",
        "        p = st.getPositions(asNumpy=True).value_in_unit(unit.nanometer)\n",
        "        dist = float(np.linalg.norm(np.asarray(p[b]) - np.asarray(p[a])))\n",
        "        rows.append({'time_ps': done * dt, 'restraint_center_nm': r0,\n",
        "                     'end_to_end_nm': dist, 'extension_nm': dist - d0,\n",
        "                     'force_pn': k * (r0 - dist) * KJ_PER_MOL_NM_IN_PN})\n",
        "    return pd.DataFrame(rows), d0",
    ),
    md(
        "### Stiffness fit\n",
        "\n",
        "Two corrections matter, and without them the fitted slope is meaningless (it\n",
        "comes out **negative** on short pulls):\n",
        "\n",
        "* skip the start of the pull until the restraint has moved further than the\n",
        "  thermal fluctuation of the end-to-end distance;\n",
        "* block-average the curve before fitting, because the instantaneous spring\n",
        "  force tracks thermal motion rather than the elastic response.",
    ),
    code(
        "def fit_stiffness(curve: pd.DataFrame) -> dict:\n",
        "    t = curve['time_ps'].to_numpy(); ext = curve['extension_nm'].to_numpy()\n",
        "    frc = curve['force_pn'].to_numpy()\n",
        "    if t.size < 10:\n",
        "        return {'available': False, 'reliable': False, 'reason': 'too few samples'}\n",
        "\n",
        "    noise = float(np.std(ext - np.polyval(np.polyfit(t, ext, 1), t)))\n",
        "    v = PROTOCOL['pull_velocity_nm_per_ps']\n",
        "    onset = t.min() + PROTOCOL['fit_noise_multiple'] * noise / v\n",
        "    m = t >= onset\n",
        "    if m.sum() < PROTOCOL['fit_block_size'] * 3:\n",
        "        m = np.ones_like(t, bool)\n",
        "\n",
        "    x, y = ext[m], frc[m]\n",
        "    blk = PROTOCOL['fit_block_size']; nb = x.size // blk\n",
        "    if nb >= 3:\n",
        "        x = x[:nb * blk].reshape(nb, blk).mean(1)\n",
        "        y = y[:nb * blk].reshape(nb, blk).mean(1)\n",
        "    slope, icpt = np.polyfit(x, y, 1)\n",
        "    pred = slope * x + icpt\n",
        "    ss_tot = float(((y - y.mean()) ** 2).sum())\n",
        "    r2 = 1 - float(((y - pred) ** 2).sum()) / ss_tot if ss_tot > 0 else 0.0\n",
        "\n",
        "    reasons = []\n",
        "    if slope <= 0:\n",
        "        reasons.append(f'negative stiffness {slope:.0f} pN/nm is unphysical')\n",
        "    if r2 < 0.5:\n",
        "        reasons.append(f'r2 {r2:.2f} below 0.5')\n",
        "    return {'available': True, 'reliable': not reasons, 'reasons': reasons,\n",
        "            'stiffness_pn_per_nm': float(slope), 'r_squared': float(r2),\n",
        "            'n_blocks': int(len(x)), 'extension_noise_nm': noise}",
    ),
    md(
        "## 7. The batch\n",
        "\n",
        "For each (protein, seed): equilibrate **once**, then run the pristine pull and\n",
        "every damaged variant from that same conformation. The baseline is shared\n",
        "across all variants of that (protein, seed), which is both cheaper and tighter\n",
        "-- baseline and damaged differ by the side chains and not by two independent\n",
        "equilibration trajectories.\n",
        "\n",
        "Results append to CSV after every experiment, so a session timeout keeps\n",
        "everything already finished. Re-running skips completed work.",
    ),
    code(
        "SEEDS = [1, 2, 3, 4, 5]        # more seeds = smaller label error (SE ~ 1/sqrt(n))\n",
        "N_MILD = 5                     # top-N eligible residues, damaged one at a time\n",
        "# A value below 1 is read as a FRACTION of the eligible residues. EXTREME\n",
        "# exists to answer one question: does stiffness respond to damage AT ALL?\n",
        "# Removing 6 of ~76 side chains (SEVERE) produced no change above noise, so\n",
        "# if EXTREME also produces none, the observable is dead at this timescale\n",
        "# and no amount of extra seeds will rescue it. That is a real result.\n",
        "SEVERITIES = {\'MILD\': 1, \'MODERATE\': 3, \'SEVERE\': 6, \'EXTREME\': 0.25}\n",
        "RESULTS_CSV = WORK / 'stiffness_results_REAL_v1.csv'\n",
        "\n",
        "def variants_for(pdb_id, pull_seqs):\n",
        "    \"\"\"(variant_id, severity, [residue_seqs]) for one protein.\"\"\"\n",
        "    df = FEATURES[pdb_id]\n",
        "    ok = [r for r in df.itertuples() if eligible(r.residue_type, r.residue_seq, pull_seqs)]\n",
        "    out = []\n",
        "    for r in ok[:N_MILD]:\n",
        "        out.append((f'MILD_{r.residue_seq}', 'MILD', [r.residue_seq]))\n",
        "    for label, n in SEVERITIES.items():\n",
        "        if label == \'MILD\':\n",
        "            continue          # enumerated one residue at a time above\n",
        "        k = max(1, round(n * len(ok))) if 0 < n < 1 else int(n)\n",
        "        if k > 1 and len(ok) >= k:\n",
        "            seqs = [r.residue_seq for r in ok[:k]]\n",
        "            out.append((f\'{label}_{seqs[0]}\', label, seqs))\n",
        "    return out\n",
        "\n",
        "def load_done():\n",
        "    if RESULTS_CSV.exists():\n",
        "        return set(pd.read_csv(RESULTS_CSV)['experiment_id'])\n",
        "    return set()\n",
        "\n",
        "def append_row(row):\n",
        "    pd.DataFrame([row]).to_csv(\n",
        "        RESULTS_CSV, mode='a', header=not RESULTS_CSV.exists(), index=False)",
    ),
    code(
        "done = load_done()\n",
        "print(f'{len(done)} experiments already complete')\n",
        "t_start = time.time()\n",
        "failed_proteins = []\n",
        "\n",
        "\n",
        "def run_protein(pdb_id, meta):\n",
        "    \"\"\"Every experiment for one protein. Baseline is shared across its variants.\"\"\"\n",
        "    chain = meta['chain']\n",
        "    prepared = WORK / f'{pdb_id}_prepared.pdb'\n",
        "    ca_seqs = sorted(FEATURES[pdb_id]['residue_seq'])\n",
        "    pull_seqs = {ca_seqs[0], ca_seqs[-1]}\n",
        "    variants = variants_for(pdb_id, pull_seqs)\n",
        "\n",
        "    for seed in SEEDS:\n",
        "        todo = [v for v in variants if f'{pdb_id}_{v[0]}_seed{seed}' not in done]\n",
        "        if not todo:\n",
        "            continue\n",
        "\n",
        "        # One shared equilibrated conformation for this (protein, seed). Baseline\n",
        "        # and damaged then differ by the side chains and NOT by two independent\n",
        "        # equilibration trajectories, which was the largest nuisance term.\n",
        "        equil = WORK / f'{pdb_id}_equil_seed{seed}.pdb'\n",
        "        if not equil.exists():\n",
        "            equilibrate(prepared, seed, PROTOCOL['shared_equilibration_steps'], equil)\n",
        "\n",
        "        base_curve, base_d0 = steered_pull(equil, seed)\n",
        "        base_fit = fit_stiffness(base_curve)\n",
        "        base_curve.to_csv(WORK / f'{pdb_id}_baseline_seed{seed}_fe.csv', index=False)\n",
        "        bk = base_fit.get('stiffness_pn_per_nm') if base_fit.get('available') else None\n",
        "\n",
        "        for variant_id, severity, seqs in todo:\n",
        "            exp_id = f'{pdb_id}_{variant_id}_seed{seed}'\n",
        "            dmg_pdb = WORK / f'{exp_id}_damaged.pdb'\n",
        "            dmg_meta = apply_damage(equil, dmg_pdb, chain, seqs)\n",
        "            try:\n",
        "                dmg_curve, _ = steered_pull(dmg_pdb, seed)\n",
        "                dmg_fit = fit_stiffness(dmg_curve)\n",
        "                dmg_curve.to_csv(WORK / f'{exp_id}_fe.csv', index=False)\n",
        "                err = ''\n",
        "            except Exception as exc:\n",
        "                dmg_fit = {'available': False, 'reliable': False}\n",
        "                err = f'{type(exc).__name__}: {exc}'\n",
        "\n",
        "            dk = dmg_fit.get('stiffness_pn_per_nm') if dmg_fit.get('available') else None\n",
        "            deg = (bk - dk) / bk * 100.0 if bk and dk is not None else None\n",
        "            ok = bool(base_fit.get('reliable') and dmg_fit.get('reliable') and not err)\n",
        "            primary = FEATURES[pdb_id].set_index('residue_seq').loc[seqs[0]]\n",
        "\n",
        "            append_row({\n",
        "                'experiment_id': exp_id, 'protein_id': pdb_id, 'pdb_id': pdb_id,\n",
        "                'chain_id': chain, 'uniprot_id': meta['uniprot'],\n",
        "                'scenario_id': 'GCR_DEEP_SPACE_REFERENCE',   # metadata only\n",
        "                'severity_label': severity,\n",
        "                'damage_residue_id': f'{chain}:{seqs[0]}',\n",
        "                'damage_residue_ids': dmg_meta['damage_residue_ids'],\n",
        "                'n_residues_damaged': dmg_meta['n_residues_damaged'],\n",
        "                'n_atoms_removed': dmg_meta['n_atoms_removed'],\n",
        "                'residue_type': primary['residue_type'],\n",
        "                'residue_index_norm': float(primary['residue_index_norm']),\n",
        "                'residue_sasa_norm': float(primary['residue_sasa_norm']),\n",
        "                'residue_contact_count': float(primary['residue_contact_count']),\n",
        "                'qualitative_susceptibility': primary['qualitative_susceptibility'],\n",
        "                'proxy_rank': int(primary['proxy_rank']),\n",
        "                'protein_length': float(primary['protein_length']),\n",
        "                'molecular_weight': float(primary['molecular_weight']),\n",
        "                'hydrophobic_fraction': float(primary['hydrophobic_fraction']),\n",
        "                'charged_fraction': float(primary['charged_fraction']),\n",
        "                'proxy_type': 'SIDE_CHAIN_LOSS', 'random_seed': seed,\n",
        "                'baseline_stiffness': bk, 'damaged_stiffness': dk,\n",
        "                'stiffness_unit': 'pN/nm',\n",
        "                'fit_quality': base_fit.get('r_squared'),\n",
        "                'damaged_fit_quality': dmg_fit.get('r_squared'),\n",
        "                'mechanical_degradation_pct': deg,\n",
        "                'baseline_end_to_end_nm': base_d0,\n",
        "                'status': 'COMPLETED' if ok else 'QC_FAILED',\n",
        "                'qc_note': err or ' | '.join(\n",
        "                    base_fit.get('reasons', []) + dmg_fit.get('reasons', [])),\n",
        "                'sim_config_hash': PROTOCOL_HASH, 'is_synthetic': False,\n",
        "            })\n",
        "            done.add(exp_id)\n",
        "            print(f'{exp_id:32} base={None if bk is None else round(bk)} '\n",
        "                  f'dmg={None if dk is None else round(dk)} '\n",
        "                  f'deg={None if deg is None else round(deg, 1)} '\n",
        "                  f'[{\"OK\" if ok else \"QC\"}] {(time.time() - t_start) / 60:.0f}m')\n",
        "\n",
        "\n",
        "for pdb_id, meta in PROTEINS.items():\n",
        "    try:\n",
        "        run_protein(pdb_id, meta)\n",
        "    except Exception as exc:\n",
        "        # One bad structure must not cost the whole session.\n",
        "        failed_proteins.append((pdb_id, f'{type(exc).__name__}: {exc}'))\n",
        "        print(f'{pdb_id}: SKIPPED -- {type(exc).__name__}: {exc}')\n",
        "\n",
        "print('\\nbatch complete:', len(done), 'experiments in',\n",
        "      f'{(time.time() - t_start) / 60:.0f} min')\n",
        "for pid, err in failed_proteins:\n",
        "    print(f'  skipped {pid}: {err}')",
    ),
    md(
        "## 8. Labels with uncertainty\n",
        "\n",
        "One pull is one draw from a stochastic process. Averaging n seeds shrinks the\n",
        "label's standard error by sqrt(n); the SE is reported so a label that is still\n",
        "too noisy can be excluded instead of silently trained on.",
    ),
    code(
        "if RESULTS_CSV.exists():\n",
        "    raw = pd.read_csv(RESULTS_CSV).drop_duplicates('experiment_id')\n",
        "else:\n",
        "    raw = pd.DataFrame()\n",
        "    print('No results file yet. Run the batch cell above first.')\n",
        "\n",
        "ok = (raw[(raw['status'] == 'COMPLETED') & raw['mechanical_degradation_pct'].notna()]\n",
        "      if len(raw) else raw)\n",
        "print(f'{len(raw)} experiments, {len(ok)} passed QC ({len(ok)/max(len(raw),1):.0%})')\n",
        "\n",
        "GROUP = ['protein_id', 'severity_label', 'damage_residue_ids']\n",
        "FEATURE_COLS = ['protein_length', 'molecular_weight', 'hydrophobic_fraction',\n",
        "                'charged_fraction', 'residue_index_norm', 'residue_sasa_norm',\n",
        "                'residue_contact_count', 'proxy_rank', 'n_residues_damaged',\n",
        "                'n_atoms_removed', 'baseline_end_to_end_nm']\n",
        "CAT_COLS = ['residue_type', 'qualitative_susceptibility', 'severity_label']\n",
        "\n",
        "MIN_SEEDS, MAX_SEM = 3, 15.0\n",
        "if len(ok) == 0:\n",
        "    agg = pd.DataFrame(columns=GROUP + ['n_seeds', 'target', 'target_std',\n",
        "                                        'target_sem', 'usable'])\n",
        "    print('\\nNothing passed QC, so there is nothing to aggregate. Check the\\n'\n",
        "          'qc_note column in the results CSV before changing the protocol.')\n",
        "else:\n",
        "  agg = ok.groupby(GROUP).agg(\n",
        "      n_seeds=('mechanical_degradation_pct', 'size'),\n",
        "      target=('mechanical_degradation_pct', 'mean'),\n",
        "      target_std=('mechanical_degradation_pct', 'std'),\n",
        "      baseline_mean=('baseline_stiffness', 'mean'),\n",
        "      damaged_mean=('damaged_stiffness', 'mean'),\n",
        "      **{c: (c, 'first') for c in FEATURE_COLS + CAT_COLS},\n",
        "  ).reset_index()\n",
        "  agg['target_sem'] = agg['target_std'] / np.sqrt(agg['n_seeds'])\n",
        "\n",
        "  agg['usable'] = (agg['n_seeds'] >= MIN_SEEDS) & (agg['target_sem'] <= MAX_SEM)\n",
        "\n",
        "if len(agg):\n",
        "    print(f\"\\n{len(agg)} perturbations, {int(agg['usable'].sum())} usable \"\n",
        "          f\"(n>={MIN_SEEDS}, SE<={MAX_SEM} pp)\")\n",
        "    typical = agg['target_std'].median()\n",
        "    if typical and not math.isnan(typical):\n",
        "        print(f'median per-perturbation label std: {typical:.1f} pp')\n",
        "        for tgt in (10, 5, 2):\n",
        "            print(f'  seeds needed for SE +/-{tgt} pp: "
        "{math.ceil((typical/tgt)**2)}')\n",
        "    else:\n",
        "        print('Only one seed per perturbation: the label error is unknown. '\n",
        "              'Raise SEEDS and re-run the batch.')\n",
        "agg.sort_values('target').head(12) if len(agg) else agg",
    ),
    md(
        "## 9. Model\n",
        "\n",
        "**GroupKFold by protein.** Random splits would put the same protein in train and\n",
        "test and report a number that does not survive contact with a new protein.\n",
        "\n",
        "The label's own standard error puts a ceiling on achievable R2. The cell below\n",
        "computes that ceiling and compares the model to it, so a mediocre R2 can be read\n",
        "correctly: it may be the label noise, not the model.",
    ),
    code(
        "from sklearn.model_selection import GroupKFold\n",
        "from sklearn.metrics import mean_absolute_error, r2_score\n",
        "from sklearn.dummy import DummyRegressor\n",
        "import xgboost as xgb\n",
        "\n",
        "# astype(bool) matters: on an empty frame that column is object dtype,\n",
        "# and pandas then reads the mask as column selection, not a row filter.\n",
        "train = agg[agg[\'usable\'].astype(bool)].copy() if len(agg) else agg.copy()\n",
        "n_groups = train[\'protein_id\'].nunique() if len(train) else 0\n",
        "if len(train) < 10 or n_groups < 3:\n",
        "    print(f\'Only {len(train)} usable labels across {n_groups} proteins. \'\n",
        "          \'Increase SEEDS and re-run the batch: there is not enough \'\n",
        "          \'signal-to-noise to train a model yet.\')\n",
        "else:\n",
        "    X = pd.get_dummies(train[FEATURE_COLS + CAT_COLS], columns=CAT_COLS)\n",
        "    y = train['target'].to_numpy()\n",
        "    groups = train['protein_id']\n",
        "    n_splits = min(5, groups.nunique())\n",
        "\n",
        "    preds = np.zeros(len(y)); base_preds = np.zeros(len(y))\n",
        "    for tr, te in GroupKFold(n_splits=n_splits).split(X, y, groups):\n",
        "        model = xgb.XGBRegressor(\n",
        "            n_estimators=300, max_depth=3, learning_rate=0.05,\n",
        "            subsample=0.9, colsample_bytree=0.8, reg_lambda=1.0,\n",
        "            random_state=42, n_jobs=4)\n",
        "        model.fit(X.iloc[tr], y[tr])\n",
        "        preds[te] = model.predict(X.iloc[te])\n",
        "        base_preds[te] = DummyRegressor(strategy='mean').fit(X.iloc[tr], y[tr]).predict(X.iloc[te])\n",
        "\n",
        "    signal_var = float(np.var(y)); noise_var = float(np.mean(train['target_sem'] ** 2))\n",
        "    ceiling = max(0.0, 1 - noise_var / signal_var) if signal_var > 0 else 0.0\n",
        "\n",
        "    print(f'held-out-protein CV over {n_splits} folds, {len(y)} labels\\n')\n",
        "    print(f\"  model    MAE {mean_absolute_error(y, preds):7.2f} pp   R2 {r2_score(y, preds):6.3f}\")\n",
        "    print(f\"  mean-only MAE {mean_absolute_error(y, base_preds):7.2f} pp   R2 {r2_score(y, base_preds):6.3f}\")\n",
        "    print(f'\\n  label-noise R2 ceiling: {ceiling:.3f}')\n",
        "    print(f'  (label SE {np.sqrt(noise_var):.1f} pp vs target spread {np.sqrt(signal_var):.1f} pp)')\n",
        "    if r2_score(y, preds) <= r2_score(y, base_preds):\n",
        "        print('\\n  The model does not beat predicting the mean. Report that plainly:')\n",
        "        print('  with this much label noise it is the expected outcome, not a bug.')\n",
        "\n",
        "    full = xgb.XGBRegressor(n_estimators=300, max_depth=3, learning_rate=0.05,\n",
        "                            random_state=42).fit(X, y)\n",
        "    imp = pd.Series(full.feature_importances_, index=X.columns).sort_values(ascending=False)\n",
        "    print('\\ntop features:'); print(imp.head(10).to_string())",
    ),
    md(
        "## 10. Export a real model bundle\n",
        "\n",
        "This replaces `bionano_mock_model_bundle.pkl`. The bundle format matches what\n",
        "`app/ml/loader.py` expects, so it drops into the running app.\n",
        "\n",
        "The point of the replacement is **not a higher score**. The mock reports\n",
        "R2 = 0.84 on `SYNTHETIC_PUBLIC_DATA_PROXY` labels -- a number describing how\n",
        "well it learned an invented formula. A model trained on real paired\n",
        "simulations with a modest R2 and an honest error bar is scientifically\n",
        "stronger than that, and that is the bar being cleared here.\n",
        "\n",
        "`scientifically_validated` is set by explicit criteria, not by hand. If the\n",
        "run does not meet them the bundle still exports, flagged false, with the\n",
        "reasons recorded -- which is a real model with a disclosed limitation, not a\n",
        "mock.\n",
    ),
    code(
        "import joblib\n",
        "from sklearn.compose import ColumnTransformer\n",
        "from sklearn.pipeline import Pipeline\n",
        "from sklearn.preprocessing import OneHotEncoder, StandardScaler\n",
        "\n",
        "# Criteria for calling the model validated. Deliberately explicit: a reviewer can\n",
        "# check each one, and the bundle records which failed.\n",
        "VALIDATION_CRITERIA = {\n",
        "    'min_labels': 30,\n",
        "    'min_proteins': 8,\n",
        "    'max_label_sem_pp': 10.0,\n",
        "    'must_beat_mean_baseline': True,\n",
        "}\n",
        "\n",
        "if not len(train) or n_groups < 2:\n",
        "    print('No usable labels, so there is no real model to export.')\n",
        "    print('The mock bundle stays in place -- correctly, since nothing has replaced it.')\n",
        "else:\n",
        "    y_all = train['target'].to_numpy()\n",
        "    X_raw = train[FEATURE_COLS + CAT_COLS].copy()\n",
        "\n",
        "    # Preprocessing is bundled, so the app calls pipeline.predict(DataFrame) and\n",
        "    # never re-implements the transforms.\n",
        "    pre = ColumnTransformer([\n",
        "        ('num', StandardScaler(), FEATURE_COLS),\n",
        "        ('cat', OneHotEncoder(handle_unknown='ignore'), CAT_COLS),\n",
        "    ])\n",
        "    pipeline = Pipeline([\n",
        "        ('preprocessor', pre),\n",
        "        ('model', xgb.XGBRegressor(n_estimators=300, max_depth=3, learning_rate=0.05,\n",
        "                                   subsample=0.9, colsample_bytree=0.8,\n",
        "                                   reg_lambda=1.0, random_state=42)),\n",
        "    ]).fit(X_raw, y_all)\n",
        "\n",
        "    cv_r2 = r2_score(y_all, preds) if 'preds' in dir() else None\n",
        "    cv_mae = mean_absolute_error(y_all, preds) if 'preds' in dir() else None\n",
        "    base_r2 = r2_score(y_all, base_preds) if 'base_preds' in dir() else None\n",
        "\n",
        "    failed = []\n",
        "    if len(train) < VALIDATION_CRITERIA['min_labels']:\n",
        "        failed.append(f\"only {len(train)} labels, need {VALIDATION_CRITERIA['min_labels']}\")\n",
        "    if n_groups < VALIDATION_CRITERIA['min_proteins']:\n",
        "        failed.append(f\"only {n_groups} proteins, need {VALIDATION_CRITERIA['min_proteins']}\")\n",
        "    worst_sem = float(train['target_sem'].max())\n",
        "    if worst_sem > VALIDATION_CRITERIA['max_label_sem_pp']:\n",
        "        failed.append(f'worst label SE {worst_sem:.1f} pp exceeds '\n",
        "                      f\"{VALIDATION_CRITERIA['max_label_sem_pp']} pp\")\n",
        "    if cv_r2 is not None and base_r2 is not None and cv_r2 <= base_r2:\n",
        "        failed.append(f'held-out R2 {cv_r2:.3f} does not beat the mean baseline '\n",
        "                      f'{base_r2:.3f}')\n",
        "\n",
        "    validated = not failed\n",
        "\n",
        "    metadata = {\n",
        "        'model_name': 'BioNano-Sim Real Simulation Model',\n",
        "        'model_version': '1.0.0-real',\n",
        "        'scientific_status': 'REAL_PAIRED_SIMULATION_LABELS',\n",
        "        'label_source': 'BIONANO_PAIRED_STEERED_MD',\n",
        "        'scientifically_validated': validated,\n",
        "        'validation_criteria': VALIDATION_CRITERIA,\n",
        "        'validation_failures': failed,\n",
        "        'approved_use': ('SCIENTIFIC_INFERENCE_WITHIN_STATED_LIMITS' if validated\n",
        "                         else 'RESEARCH_PREVIEW_LIMITATIONS_DISCLOSED'),\n",
        "        'target_column': 'mechanical_degradation_pct',\n",
        "        'target_definition': ('(baseline_stiffness - damaged_stiffness) / '\n",
        "                              'baseline_stiffness * 100, from paired steered-MD pulls'),\n",
        "        'target_unit': 'percent',\n",
        "        'stiffness_unit': 'pN/nm',\n",
        "        'feature_columns': FEATURE_COLS + CAT_COLS,\n",
        "        'numeric_features': FEATURE_COLS,\n",
        "        'categorical_features': CAT_COLS,\n",
        "        'n_training_labels': int(len(train)),\n",
        "        'n_proteins': int(n_groups),\n",
        "        'proteins': sorted(train['protein_id'].unique().tolist()),\n",
        "        'seeds_per_label_median': float(train['n_seeds'].median()),\n",
        "        'label_sem_pp_median': float(train['target_sem'].median()),\n",
        "        'label_sem_pp_max': worst_sem,\n",
        "        'cv_scheme': 'GroupKFold by protein (held-out protein)',\n",
        "        'cv_r2': None if cv_r2 is None else float(cv_r2),\n",
        "        'cv_mae_pp': None if cv_mae is None else float(cv_mae),\n",
        "        'mean_baseline_r2': None if base_r2 is None else float(base_r2),\n",
        "        'label_noise_r2_ceiling': float(ceiling) if 'ceiling' in dir() else None,\n",
        "        'sim_config_hash': PROTOCOL_HASH,\n",
        "        'protocol': PROTOCOL,\n",
        "        'excluded_features': {\n",
        "            'scenario_id': ('does not enter the simulation, so it carries no signal '\n",
        "                            'and would be fitted to noise'),\n",
        "            'dose_gy / let / fluence': ('not consumed by the simulation and not '\n",
        "                                        'verified against NASA references'),\n",
        "        },\n",
        "        'limitations': [\n",
        "            'Radiation is not simulated. The damage proxy is a side-chain truncation '\n",
        "            'at residues selected for literature radiosensitivity.',\n",
        "            'Pulls are 40 ps of non-equilibrium steered MD, ~1e6 times faster than an '\n",
        "            'AFM experiment. Absolute forces are not comparable to experiment.',\n",
        "            'Severity is a count of removed side chains and is not a dose.',\n",
        "            'The target carries measurable run-to-run noise; see label_sem_pp_median.',\n",
        "        ],\n",
        "        'created_at_utc': pd.Timestamp.utcnow().isoformat(),\n",
        "    }\n",
        "\n",
        "    bundle = {\n",
        "        'pipeline': pipeline,\n",
        "        'metadata': metadata,\n",
        "        'feature_columns': FEATURE_COLS + CAT_COLS,\n",
        "        'target_column': 'mechanical_degradation_pct',\n",
        "        'model_version': metadata['model_version'],\n",
        "        'scientific_status': metadata['scientific_status'],\n",
        "    }\n",
        "\n",
        "    bundle_path = WORK / 'bionano_real_model_bundle.pkl'\n",
        "    joblib.dump(bundle, bundle_path, compress=3)\n",
        "    digest = hashlib.sha256(bundle_path.read_bytes()).hexdigest()\n",
        "\n",
        "    (WORK / 'model_metadata.json').write_text(json.dumps(metadata, indent=2, default=str))\n",
        "    (WORK / 'release_manifest.json').write_text(json.dumps({\n",
        "        'model_file': bundle_path.name,\n",
        "        'model_sha256': digest,\n",
        "        'metadata_file': 'model_metadata.json',\n",
        "        'scientific_status': metadata['scientific_status'],\n",
        "        'created_at_utc': metadata['created_at_utc'],\n",
        "    }, indent=2, default=str))\n",
        "\n",
        "    print(f\"exported {bundle_path.name}  ({bundle_path.stat().st_size:,} bytes)\")\n",
        "    print(f\"  sha256               {digest[:32]}...\")\n",
        "    print(f\"  status               {metadata['scientific_status']}\")\n",
        "    print(f\"  labels / proteins    {len(train)} / {n_groups}\")\n",
        "    print(f\"  held-out R2          {cv_r2}\")\n",
        "    print(f\"  scientifically_validated: {validated}\")\n",
        "    for reason in failed:\n",
        "        print(f'    unmet: {reason}')\n",
        "    print('\\nTo install: copy the three files into models/ and update the app config.')",
    ),
    md(
        "## 11. Export\n",
        "\n",
        "`stiffness_results_REAL_v1.csv` is the per-experiment table for the ML team.\n",
        "`ml_training_labels_v1.csv` is the aggregated, uncertainty-quantified version.",
    ),
    code(
        "agg.to_csv(WORK / 'ml_training_labels_v1.csv', index=False)\n",
        "summary = {\n",
        "    'experiments': int(len(raw)), 'passed_qc': int(len(ok)),\n",
        "    'perturbations': int(len(agg)),\n",
        "    'usable_labels': int(agg['usable'].sum()) if len(agg) else 0,\n",
        "    'median_label_std_pp': (float(agg['target_std'].median())\n",
        "                            if len(agg) else None),\n",
        "    'seeds_run': SEEDS, 'protocol': PROTOCOL, 'sim_config_hash': PROTOCOL_HASH,\n",
        "    'scenario_note': 'scenario_id does not enter the simulation and must not be a feature',\n",
        "    'is_synthetic': False,\n",
        "}\n",
        "(WORK / 'run_summary.json').write_text(json.dumps(summary, indent=2, default=str))\n",
        "print(json.dumps({k: v for k, v in summary.items() if k != 'protocol'}, indent=2))\n",
        "print('\\nfiles in /kaggle/working:')\n",
        "for f in sorted(WORK.glob('*.csv'))[:10]:\n",
        "    print(' ', f.name)",
    ),
]

NOTEBOOK = {
    "cells": CELLS,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
        "accelerator": "GPU",
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

OUT.write_text(json.dumps(NOTEBOOK, indent=1), encoding="utf-8")
print(f"wrote {OUT} ({OUT.stat().st_size:,} bytes, {len(CELLS)} cells)")
