"""The feature contract, loaded from ``models/feature_schema.json``.

``models/feature_schema.json`` is generated by
``scripts/generate_feature_schema.py`` directly from the pickled pipeline, so
the vocabularies here are the encoder's own categories rather than a
hand-maintained copy. At load time we re-verify the file against the live
pipeline and refuse to start if they disagree (see :mod:`app.ml.loader`).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

from app.config import settings


@dataclass(frozen=True)
class Bounds:
    min: float
    max: float

    def contains(self, value: float) -> bool:
        return self.min <= value <= self.max


@dataclass(frozen=True)
class FeatureSchema:
    """Immutable view over the generated schema document."""

    raw: dict[str, Any]

    # --- Column layout ------------------------------------------------------
    @property
    def feature_order(self) -> list[str]:
        """The 14 columns, in the order the pipeline expects them."""
        return list(self.raw["feature_order"])

    @property
    def numeric_features(self) -> list[str]:
        return list(self.raw["numeric_features"])

    @property
    def categorical_features(self) -> list[str]:
        return list(self.raw["categorical_features"])

    @property
    def target_column(self) -> str:
        return str(self.raw["target_column"])

    # --- Vocabularies and ranges -------------------------------------------
    @property
    def vocabulary(self) -> dict[str, list[str]]:
        return {k: list(v) for k, v in self.raw["categorical_vocabulary"].items()}

    def allowed_values(self, column: str) -> list[str]:
        return list(self.raw["categorical_vocabulary"].get(column, []))

    def hard_bounds(self, column: str) -> Bounds | None:
        b = self.raw["numeric_hard_bounds"].get(column)
        return Bounds(float(b["min"]), float(b["max"])) if b else None

    def train_envelope(self, column: str) -> Bounds | None:
        b = self.raw["numeric_train_envelope"].get(column)
        return Bounds(float(b["min"]), float(b["max"])) if b else None

    @property
    def target_train_range(self) -> Bounds:
        r = self.raw["target_observed_range"]["train"]
        return Bounds(float(r["min"]), float(r["max"]))

    @property
    def clamp(self) -> Bounds:
        c = self.raw["output_clamp"]
        return Bounds(float(c["min"]), float(c["max"]))

    # --- Model identity -----------------------------------------------------
    @property
    def model_version(self) -> str:
        return str(self.raw["model_version"])

    @property
    def scientific_status(self) -> str:
        return str(self.raw["scientific_status"])

    @property
    def bundle_sha256(self) -> str:
        return str(self.raw["bundle_sha256"])

    @property
    def supports_uncertainty(self) -> bool:
        return bool(self.raw["supports_uncertainty"])

    @property
    def uncertainty_note(self) -> str:
        return str(self.raw["uncertainty_note"])

    # --- Derived-feature formulas (used to featurise uploads) --------------
    @property
    def formulas(self) -> dict[str, Any]:
        return dict(self.raw["derived_feature_formulas"])

    @property
    def hydrophobic_set(self) -> set[str]:
        return set(self.formulas["hydrophobic_set"])

    @property
    def charged_set(self) -> set[str]:
        return set(self.formulas["charged_set"])

    @property
    def susceptibility_score_map(self) -> dict[str, float]:
        return {k: float(v) for k, v in self.formulas["susceptibility_score_map"].items()}

    @property
    def susceptibility_by_residue(self) -> dict[str, str]:
        """Invert the grouped mapping into ``{'TRP': 'high', ...}``."""
        out: dict[str, str] = {}
        for level, residues in self.formulas[
            "qualitative_susceptibility_by_residue"
        ].items():
            for r in residues:
                out[r] = level
        return out


@lru_cache
def load_feature_schema(path: Path | None = None) -> FeatureSchema:
    target = path or settings.feature_schema_path
    if not target.exists():
        raise FileNotFoundError(
            f"Feature schema not found at {target}. "
            "Regenerate it with: python scripts/generate_feature_schema.py"
        )
    return FeatureSchema(json.loads(target.read_text(encoding="utf-8")))
