#!/usr/bin/env python
"""Regenerate models/feature_schema.json from the model bundle and training splits.

Every vocabulary and bound written by this script is read out of the pickled
pipeline itself, so the schema the API validates against can never drift from the
model it is validating for. Run it after replacing the bundle.

    python scripts/generate_feature_schema.py
"""

from __future__ import annotations

import hashlib
import json
import sys
import warnings
from pathlib import Path

# scripts/ is not a package, so the shared console helper is imported by
# path. init_console() must run before any output is written.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _console import init_console  # noqa: E402

init_console()

warnings.filterwarnings("ignore")

REPO = Path(__file__).resolve().parents[1]

# Physically/structurally admissible input ranges. Deliberately wider than the
# training envelope: out-of-envelope input produces a warning, not a rejection.
HARD_BOUNDS = {
    "protein_length": {"min": 1, "max": 10000},
    "molecular_weight": {"min": 0.0, "max": 2.0e6},
    "hydrophobic_fraction": {"min": 0.0, "max": 1.0},
    "charged_fraction": {"min": 0.0, "max": 1.0},
    "residue_index_norm": {"min": 0.0, "max": 1.0},
    "residue_sasa_norm": {"min": 0.0, "max": 1.0},
    "residue_contact_count": {"min": 0, "max": 500},
    "proxy_rank": {"min": 1, "max": 10000},
}

DERIVED = {
    "_comment": (
        "Reverse-engineered from data/ml/data/*.csv and verified against all five "
        "approved proteins. Used to featurise UPLOADED structures; approved proteins "
        "read the precomputed training table instead."
    ),
    "residue_inclusion_rule": (
        "standard amino acid AND hetflag == ' ' AND has a CA atom (this excludes e.g. "
        "1TEN A:802, an ARG with only C and O)"
    ),
    "hydrophobic_set": ["A", "F", "I", "L", "M", "V", "W", "Y"],
    "charged_set": ["D", "E", "K", "R"],
    "residue_index_norm": "i / (n - 1), i zero-based over kept residues",
    "residue_contact_count": (
        "count of Ca atoms within 8.0 A, self excluded (reproduces reference table exactly)"
    ),
    "residue_sasa_norm": (
        "per-chain min-max normalised Shrake-Rupley SASA (probe 1.40 A, 100 points, "
        "hydrogens stripped, chain in isolation). APPROXIMATE: correlates r=0.93 (1UBQ) "
        "/ 0.98 (1PGA) / 0.99 (1TIT) with the reference table but is not bit-identical."
    ),
    "inverse_packing": (
        "1 - residue_contact_count / max(residue_contact_count) within the protein"
    ),
    "susceptibility_score_map": {"high": 1.0, "medium": 0.6, "low": 0.25},
    "qualitative_susceptibility_by_residue": {
        "high": ["CYS", "HIS", "MET", "TRP", "TYR"],
        "medium": ["ARG", "ASN", "GLN", "LYS", "PHE", "PRO", "SER", "THR"],
        "low": ["ALA", "ASP", "GLU", "GLY", "ILE", "LEU", "VAL"],
    },
    "candidate_score": (
        "0.45*residue_sasa_norm + 0.30*inverse_packing + 0.25*susceptibility_score "
        "(verified exact to 1.1e-16 over all 50 ranked rows)"
    ),
    "proxy_rank": (
        "1-based descending rank of candidate_score within the protein; the training "
        "set uses the top 10"
    ),
}


def main() -> int:
    import joblib
    import pandas as pd

    bundle_path = REPO / "models" / "COSMORA_mock_model_bundle.pkl"
    if not bundle_path.exists():
        print(f"ERROR: model bundle not found at {bundle_path}", file=sys.stderr)
        return 1

    bundle = joblib.load(bundle_path)
    pipeline = bundle["pipeline"]
    pre = pipeline.named_steps["preprocessor"]
    num_cols = list(pre.transformers_[0][2])
    cat_cols = list(pre.transformers_[1][2])
    encoder = pre.transformers_[1][1].named_steps["encoder"]
    imputer = pre.transformers_[0][1].named_steps["imputer"]

    train = pd.read_csv(REPO / "data" / "ml" / "splits" / "train.csv")
    full = pd.read_csv(REPO / "data" / "ml" / "data" / "COSMORA_mock_experiments_v1.csv")
    target = bundle["target_column"]

    schema = {
        "_comment": (
            "GENERATED by scripts/generate_feature_schema.py from the model bundle and "
            "training splits. Do not hand-edit."
        ),
        "model_version": bundle["model_version"],
        "scientific_status": bundle["scientific_status"],
        "bundle_sha256": hashlib.sha256(bundle_path.read_bytes()).hexdigest(),
        "sklearn_version_at_fit": "1.7.1",
        "target_column": target,
        "feature_order": list(bundle["feature_columns"]),
        "numeric_features": num_cols,
        "categorical_features": cat_cols,
        "n_transformed_features": len(pre.get_feature_names_out()),
        "transformed_feature_names": [str(x) for x in pre.get_feature_names_out()],
        "unknown_category_policy": {
            "encoder_handle_unknown": encoder.handle_unknown,
            "effect": (
                "An unseen category is encoded as an all-zero block. The model still "
                "returns a number, so unknown categories MUST be detected before "
                "predicting and reported as a warning."
            ),
        },
        "categorical_vocabulary": {
            c: [str(v) for v in cats] for c, cats in zip(cat_cols, encoder.categories_, strict=False)
        },
        "numeric_imputer_medians": {
            c: float(v) for c, v in zip(num_cols, imputer.statistics_, strict=False)
        },
        "numeric_train_envelope": {
            c: {"min": float(train[c].min()), "max": float(train[c].max())}
            for c in num_cols
        },
        "numeric_hard_bounds": HARD_BOUNDS,
        "target_observed_range": {
            "train": {"min": float(train[target].min()), "max": float(train[target].max())},
            "full_data": {"min": float(full[target].min()), "max": float(full[target].max())},
        },
        "output_clamp": {
            "min": 0.0,
            "max": 100.0,
            "justification": (
                "The target is a percentage, so values outside [0,100] are physically "
                "meaningless. Gradient-boosted trees cannot extrapolate beyond the "
                "training target range anyway, so this clamp is defensive only; every "
                "clamp event is reported in the response warnings."
            ),
        },
        "supports_uncertainty": False,
        "uncertainty_note": (
            "The bundle exposes no predict_proba, no quantile heads and no calibrated "
            "interval, so per-prediction confidence is reported as null. Held-out error "
            "from model_metadata.json (validation MAE 4.11 pp on unseen 1UBQ; test MAE "
            "2.26 pp on unseen 1TEN) is a retrospective dataset-level metric and is NOT "
            "a per-prediction confidence."
        ),
        "derived_feature_formulas": DERIVED,
    }

    out = REPO / "models" / "feature_schema.json"
    out.write_text(json.dumps(schema, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {out.relative_to(REPO)}")
    print(f"  features    : {len(schema['feature_order'])} -> {schema['n_transformed_features']} transformed")
    sizes = {k: len(v) for k, v in schema["categorical_vocabulary"].items()}
    print(f"  vocabularies: {sizes}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
